### ISSUE TITLE
Project doesn't compile with Gradle 2.12

### ISSUE THREAD

**Issue by donkike** [Frege/frege-gradle-plugin#36]
I'm getting an error when running `gradle build`with Gradle 2.12:

`java.lang.NoSuchMethodError: org.gradle.api.internal.file.DefaultSourceDirectorySet.<init>(Ljava/lang/String;Lorg/gradle/api/internal/file/FileResolver;)`

I looked online and it seems to be related to a change in the internal API with Gradle 2.12, as explained here https://bitbucket.org/clojuresque/clojuresque/issues/4/plugin-stops-working-in-gradle-212.

**Comment by Dierk** [comment]
Thanks for reporting. 
The issue is fixed but the fix is not yet in the distribution. 

Cheers 
Dierk

sent from:mobile
